### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ReallySub** [ReallySub/Weeping-Angels-Mod#14]
- [x] Config for blocks (Determining which blocks to break and which not to)
- [x] Dimension config
- [ ] Make generator effect look better
- [ ] Saving a pos per angel (So a angel gets a random blockpos and dimension and retains those per it's own life cycle)
- [x] Damage config option
- [x] Speed config option
- [x] Compatiblity with other mods
